name: teamstream
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.8
  go_router: ^14.8.0
  flutter_bloc: ^9.0.0
  pocketbase: ^0.21.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.1
  file_picker: ^8.3.2
  open_file: ^3.5.10
  intl: ^0.19.0 # Downgraded to be compatible with Syncfusion
  uuid: ^4.5.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  provider: ^6.1.2
  connectivity_plus: ^6.1.3
  url_launcher: ^6.3.1
  http: 1.3.0 # Downgraded to be compatible with Syncfusion
  flutter_inappwebview: ^6.1.5
  google_ml_kit: ^0.19.0
  image: ^4.5.3
  csv: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  cached_network_image: ^3.4.1
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.2.1
  camera: ^0.11.1
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.1
  animate_do: ^4.2.0
  flutter_spinkit: ^5.2.1

  # Syncfusion dependencies for PDF handling and charts
  syncfusion_flutter_pdf: ^26.2.10
  syncfusion_flutter_pdfviewer: ^26.2.10
  syncfusion_flutter_charts: ^26.2.10
  printing: ^5.14.0
  fl_chart: ^0.70.2
  flutter_pdfview: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true